all: dis-sender sender-node receiver-node root-node
CONTIKI=~/contiki-ng

MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

MAKE_MAC = MAKE_MAC_CSMA

#MODULES +=os/services/orchestra

include $(CONTIKI)/Makefile.include
